import re
import string
import secrets
from cryptography.fernet import Fernet
from supabase import create_client, Client

# Configuration
SUPABASE_URL= ""
SUPABASE_KEY= ""

ENCRYPTION_KEY = Fernet.generate_key() #IMPORTANT: If user loses this key, the password is lost forever!
cipher_suite = Fernet(ENCRYPTION_KEY)

# Initializing Cloud Database
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

# Main Code Starts
MIN_LENGTH = 14
SPECIAL_CHARS = string.punctuation

def analyse_strength(password):
    score = 0

    if len(password) >= MIN_LENGTH:
        score += 1
    if re.search(r"[A-Z]", password):
        score += 1
    if re.search(r"\d", password):
        score += 1
    if re.search(r"[" + re.escape(SPECIAL_CHARS) +r"]", password):
        score += 1
    return score

def generate_secured_password(length = 18):
    alphabet = string.ascii_letters + string.digits + SPECIAL_CHARS
    while True:
        password = ''.join(secrets.choice(alphabet) for _ in range (length))

        if(any(c.islower() for c in password)
           and any(c.isupper() for c in password)
           and sum(c.isdigit() for c in password)
           and any (c in SPECIAL_CHARS for c in password)):
            return password
        
def encrypt_and_store(password):
    try:
        #Encryption
        encrypted_bytes = cipher_suite.encrypt(password.encode())
        encrypted_string = encrypted_bytes.decode()

        # Storing in Cloud
        data = {"content": encrypted_string, "note": "Generated by Password_Auditor!"}
        response = supabase.table("passwords").insert(data).execute()

        print(f"\n[SUCCESS] Password Encrypted and Saved to Cloud ID: {response.data[0]["id"]}.")
        return True
    except Exception as e:
        print(f"\n[FAILED] Couldn't Save to Cloud: {e}.")
        return False
        

while True:
    print("---Password Auditor---\n")
    user_input = input("Enter the Password to test (or q to quit): ")

    if user_input.lower() == "q":
        print("\nExiting Program. Stay Secure!")
        break
    
    strength_score = analyse_strength(user_input)

    if strength_score == 4:
        print("\nExcellent! Your Password Is Secure :)")
    else:
        print(f"\nOpps! Your Password got {strength_score}/4 Checks!")
        print("\nIt's Super Vulnerable!")

        ask_user = input("\nWould you like to Generate a Strong Password (y/n): ")
        if ask_user.lower() in ["yes", "y"]:
            print("\n---GENERATING---")
            suggested_password = generate_secured_password()
            print(f"\nSuggested Password: {suggested_password}\n")
        else:
            print("\nThank You For Using Password Audit!\n")
            continue